# Generated by Django 5.1.4 on 2025-01-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_authorsubscription_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
    ]
